"""Make movie title unique

Revision ID: 43e28d3813fd
Revises: 084e00db41ef
Create Date: 2024-07-20 00:53:08.456626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e28d3813fd'
down_revision: Union[str, None] = '084e00db41ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_title', table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    # ### end Alembic commands ###
